# Generated by Django 5.0.6 on 2024-07-31 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_number', models.CharField(blank=True, null=True)),
                ('is_refered', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('prescription', models.FileField(null=True, upload_to='pdf/')),
                ('treatment_detail', models.TextField(null=True)),
                ('duration', models.IntegerField()),
                ('is_threapytaken', models.BooleanField(default=False)),
                ('first_time', models.BooleanField(default=True)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
            ],
        ),
    ]
