# Generated by Django 5.0.6 on 2024-08-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_diagnose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_charge', models.IntegerField()),
                ('threapy_charge', models.IntegerField()),
                ('other_charges', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('qr_code', models.ImageField(upload_to='image/')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.payment_status')),
            ],
        ),
    ]
