# Generated by Django 5.0.6 on 2024-08-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_payment_status_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='tax',
            field=models.IntegerField(default=50),
        ),
    ]
