# Generated by Django 5.0.6 on 2024-08-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_fee_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='qr_code',
            field=models.FileField(upload_to='image/'),
        ),
    ]
