# Generated by Django 5.0.6 on 2024-08-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_service_threapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_detail', models.TextField(max_length=100)),
                ('follow_up', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
                ('threapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.threapy')),
            ],
        ),
    ]
