# Generated by Django 5.0.6 on 2024-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
