# Generated by Django 5.0.6 on 2024-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_report_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='fee',
            name='total_amount',
            field=models.CharField(default=0),
        ),
    ]
