# Generated by Django 5.0.6 on 2024-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_report_total_amount_fee_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
