# Generated by Django 5.0.6 on 2024-08-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_report_total_amount_fee_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.fee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
            ],
        ),
    ]
